"""initial schema — documents, chunks, graph_nodes, graph_edges (PLAN §6)

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-22

Hand-written (not autogenerated): pgvector extension, the generated ``content_tsv``
column, and the HNSW/GIN indexes are outside Alembic's autogenerate support. The
embedding dimension comes from settings so it always matches the ORM Vector().
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.core.config import get_settings

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBED_DIM = get_settings().embed_dim


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    op.execute(
        """
        CREATE TABLE documents (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            source_type   TEXT NOT NULL,
            title         TEXT NOT NULL,
            uri           TEXT,
            content_hash  TEXT NOT NULL UNIQUE,
            sensitivity   TEXT NOT NULL DEFAULT 'public'
                          CHECK (sensitivity IN ('public','internal','confidential')),
            lang          TEXT NOT NULL DEFAULT 'english',
            meta          JSONB DEFAULT '{}',
            created_at    TIMESTAMPTZ DEFAULT now()
        );
        """
    )

    op.execute(
        f"""
        CREATE TABLE chunks (
            id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            document_id   UUID REFERENCES documents(id) ON DELETE CASCADE,
            chunk_index   INT NOT NULL,
            content       TEXT NOT NULL,
            lang          TEXT NOT NULL DEFAULT 'english',
            content_tsv   TSVECTOR GENERATED ALWAYS AS (
                            CASE WHEN lang = 'german'
                                 THEN to_tsvector('german'::regconfig, content)
                                 ELSE to_tsvector('english'::regconfig, content) END
                          ) STORED,
            embedding     VECTOR({EMBED_DIM}),
            embed_model   TEXT NOT NULL,
            meta          JSONB DEFAULT '{{}}'
        );
        """
    )
    op.execute(
        "CREATE INDEX idx_chunks_embedding ON chunks "
        "USING hnsw (embedding vector_cosine_ops);"
    )
    op.execute("CREATE INDEX idx_chunks_tsv ON chunks USING gin (content_tsv);")

    op.execute(
        """
        CREATE TABLE graph_nodes (
            id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            kind       TEXT NOT NULL CHECK (kind IN
                       ('repo','technology','domain','paper','concept','model','dataset')),
            name       TEXT NOT NULL,
            status     TEXT NOT NULL DEFAULT 'verified'
                       CHECK (status IN ('pending','verified','rejected')),
            first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
            meta       JSONB DEFAULT '{}',
            UNIQUE (kind, name)
        );
        """
    )

    op.execute(
        """
        CREATE TABLE graph_edges (
            source     UUID REFERENCES graph_nodes(id) ON DELETE CASCADE,
            target     UUID REFERENCES graph_nodes(id) ON DELETE CASCADE,
            relation   TEXT NOT NULL CHECK (relation IN
                       ('USES','BUILT_WITH','RELATED_TO',
                        'INTRODUCES','EVALUATES_ON','IMPROVES_ON')),
            status     TEXT NOT NULL DEFAULT 'verified'
                       CHECK (status IN ('pending','verified','rejected')),
            first_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
            weight     REAL DEFAULT 1.0,
            meta       JSONB DEFAULT '{}',
            PRIMARY KEY (source, target, relation)
        );
        """
    )
    op.execute("CREATE INDEX idx_graph_edges_target ON graph_edges (target);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS graph_edges;")
    op.execute("DROP TABLE IF EXISTS graph_nodes;")
    op.execute("DROP TABLE IF EXISTS chunks;")
    op.execute("DROP TABLE IF EXISTS documents;")
    # Extension left in place; other schemas may depend on it.
